- platform: generic
  still_image_url: http://admin:camera360@192.168.1.150/ISAPI/Streaming/channels/101/picture
  stream_source: rtsp://admin:camera360@192.168.1.150:554/Streaming/Channels/101/
  name: "Camera 1"
  
- platform: generic
  still_image_url: http://admin:camera360@192.168.1.150/ISAPI/Streaming/channels/201/picture
  stream_source: rtsp://admin:camera360@192.168.1.150:554/Streaming/Channels/201/
  name: "Camera 2"