- platform: mqtt
  name: "Đèn cho gà"
  state_topic: "stat/sonoff_t3/RESULT"  
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff_t3/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/sonoff_t3/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  # qos: 1
  # retain: true
  
- platform: mqtt
  name: "Light_Bedroom"
  state_topic: "stat/SwitchBedroom/RESULT"  
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/SwitchBedroom/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  availability_topic: "tele/SwitchBedroom/LWT"
  payload_available: "Online"
  payload_not_available: "Offline"
  # qos: 1
  # retain: true

- platform: wake_on_lan
  mac: DC:4A:3E:F1:B4:19
  name: "Tiến Dũng's PC"
  host: "192.168.1.156"
  turn_off: 
    service: shell_command.turn_off_pc
  # broadcast_address: "192.168.1.1"